
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module soc(

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// HPS //////////
	inout 		          		HPS_CONV_USB_N,
	output		    [14:0]		HPS_DDR3_ADDR,
	output		     [2:0]		HPS_DDR3_BA,
	output		          		HPS_DDR3_CAS_N,
	output		          		HPS_DDR3_CKE,
	output		          		HPS_DDR3_CK_N,
	output		          		HPS_DDR3_CK_P,
	output		          		HPS_DDR3_CS_N,
	output		     [3:0]		HPS_DDR3_DM,
	inout 		    [31:0]		HPS_DDR3_DQ,
	inout 		     [3:0]		HPS_DDR3_DQS_N,
	inout 		     [3:0]		HPS_DDR3_DQS_P,
	output		          		HPS_DDR3_ODT,
	output		          		HPS_DDR3_RAS_N,
	output		          		HPS_DDR3_RESET_N,
	input 		          		HPS_DDR3_RZQ,
	output		          		HPS_DDR3_WE_N,

	//////////// GPIO_0, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

	system u0 (
		.clk_clk                         (FPGA_CLK1_50),                         //                     clk.clk
		.memory_mem_a                    (HPS_DDR3_ADDR),                    //                  memory.mem_a
      .memory_mem_ba                   (HPS_DDR3_BA),                   //                        .mem_ba
      .memory_mem_ck                   (HPS_DDR3_CK_P),                   //                        .mem_ck
      .memory_mem_ck_n                 (HPS_DDR3_CK_N),                 //                        .mem_ck_n
      .memory_mem_cke                  (HPS_DDR3_CKE),                  //                        .mem_cke
      .memory_mem_cs_n                 (HPS_DDR3_CS_N),                 //                        .mem_cs_n
      .memory_mem_ras_n                (HPS_DDR3_RAS_N),                //                        .mem_ras_n
      .memory_mem_cas_n                (HPS_DDR3_CAS_N),                //                        .mem_cas_n
      .memory_mem_we_n                 (HPS_DDR3_WE_N),                 //                        .mem_we_n
      .memory_mem_reset_n              (HPS_DDR3_RESET_N),              //                        .mem_reset_n
      .memory_mem_dq                   (HPS_DDR3_DQ),                   //                        .mem_dq
      .memory_mem_dqs                  (HPS_DDR3_DQS_P),                  //                        .mem_dqs
      .memory_mem_dqs_n                (HPS_DDR3_DQS_N),                //                        .mem_dqs_n
      .memory_mem_odt                  (HPS_DDR3_ODT),                  //                        .mem_odt
      .memory_mem_dm                   (HPS_DDR3_DM),                   //                        .mem_dm
      .memory_oct_rzqin                (HPS_DDR3_RZQ)                 //                        .oct_rzqin
    );


endmodule
